### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by lauralindzey** [apl-ocean-engineering/sonar_image_proc#37]
While reviewing a PR this morning, I kept looking for the badge showing that the CI had passed ... and couldn't find it.

I see a .drone.yml, but it doesn't seem to be hooked up. (And I'm not sure what our Github CI system is, or I would have just submitted a PR -- all the repos I've added CI to have been Gitlab)

**Comment by amarburg** [comment]
Looks like the connection from Github to Drone was broken.   Potentially related to the "power event" a couple of weeks ago.  Manually kicking over the connection seems to have restored things.

It is an unsettling silent failure tho.

**Comment by lauralindzey** [comment]
Ugh. Thanks for checking + restarting. I'll close this issue now that I see green checks again ...
